[package]
name = "xelis-captcha"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio_with_wasm = { version = "0.7.2", features = ["rt"] }
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"

[lib]
crate-type = ["cdylib", "rlib"]
